---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
    keep_tex: TRUE
geometry: margin=1in

title: "CV"
author: Andrew Koech

jobtitle: "Masters Candidate, University of Bremen"
address: "Forststrasse 48 · 14471 · Potsdam, Germany"
fontawesome: yes
linkedin: andrewkoech
email: akoech@gmx.com
github: koechandy
#twitter: koechAndre
phone: "+49 1 777 892 226"
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 12pt
linkcolor: blue
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# **RESEARCH INTERESTS**

  + _Survival Analysis, Statistical Genomics, Machine Learning Modelling_

# **EDUCATION**

*University of Bremen* \hfill _Bremen, Germany_

  + **M.Sc** in Medical Biometry/Biostatistics \hfill Sept. 2022 - Ongoing
  
*Jomo Kenyatta University of Agriculture and Technology* \hfill _Nairobi, Kenya_

  + **B.Sc** in Biostatistics \hfill Sept. 2014 - Aug. 2018
  
      + “Spatial Analysis of Child Mortality in Kenya”
  
*Terige Secondary School* \hfill _Lessos, Kenya_

  + **Kenya Certificate of Secondary Education** \hfill Jan 2010 - Nov. 2013


# **EMPLOYMENT**

*International Cancer Institute* \hfill _Eldoret, Kenya_

  **Data Officer** \hfill Aug. 2019 - Apr. 2021
  
  + Design surveys to assess health issues in non-communicable diseases.
  + Prepare articles for publication and presentation at professional International conferences.
  + Write research proposals or grant applications for submission to external bodies.
  + Prepare tables and graphs to present clinical data and results.
  + Work with investigators to formalize analysis plans and reporting specifications.
  + Develop statistical analysis plans and write program code to analyze data using SAS/R or Stata.
  + Preparation of clinical trial documents, and responses to requests from the local Institutional Review Board, and other health authorities.

*AMPATH Oncology Institute* \hfill _Eldoret, Kenya_

  **Data Assistant** \hfill Sept. 2018 - Jul. 2019
  
  + Oversee registration of patients for cancer screening.
  + Check source data to verify its completeness and accuracy.
  + Code data as necessary prior to data entry using master coding lists.
  + Identify statistical tests for analyzing data.
  + Compile reports, charts and graphs that describe and interpret findings of analyses

*Kenya Medical Research Institute - Center for Public Health Research* \hfill _Nairobi, Kenya_

  **Intern** \hfill Jul. 2017 - Oct. 2017 
  

# **CONFERENCE PRESENTATIONS**

1. **Koech, Andrew**, Emma Achieng, Edwin Odoyo, Dennis Munene, and Fredrick Chite Asirwa.
2020.[Virtual Poster](https://doi.org/10.1158/1538-7755.DISP20-PO-249.) “Abstract PO-249: Implementing Community Cervical Mass Screenings in Low-Middle-Income Countries: A Project Implemented by the Blueprint for Success Program, International Cancer Institute in Kenya.” Cancer Epidemiology, Biomarkers & Prevention 29 (December): PO–249. 

2. Kitur, Gloria, Emmah Achieng, Fredrick Chite Asirwa, Edwin Odoyo, and **Andrew Koech**. 2020.[Virtual Poster](https://doi.org/10.1158/1538-7755.DISP20-PO-028.)
“Abstract PO-028: Role of Community Outreach Activities in Cancer Prevention in Kenya.”
Cancer Epidemiology, Biomarkers & Prevention 29 (December): PO–028. 

3. Muchiri, Anthony, Gloria Kitur, Hussein Elias, **Andrew Koech**, and Chite Asirwa. 2020.[Virtual Poster](https://doi.org/10.1158/1538-7755.DISP20-PO-047.) “Abstract
PO-047: The Role of Virtual Tumor Boards in Improving Patient Outcomes in Rural Settings
of Sub-Saharan Africa.” Cancer Epidemiology, Biomarkers & Prevention 29 (December): PO–047.

4. Sigu, Lamech, Fredrick Chite, Emma Achieng, and **Andrew Koech**. 2020.[Virtual Poster](https://doi.org/10.1200/GO.20.54000) “Setting up
Telemedicine: Internet of Things to Support Rural Oncology Clinics in a Low- and Middle-
Income Country—a Pilot Project in Kenya.” 6 (July):58–58.

5. **Andrew Koech**, Rose Njogu, Emma Achieng, Gloria Kitur, Chizi Kiti, Chite Asirwa.“Abstract : Setting Up Tools for Collecting Quality Data at The International Cancer Institute, Kenya - Learning from other Cancer Institutes, Registries and Cancer Clinics.”2020.[Conference canceled](https://www.dropbox.com/s/lq0owvwya6dcjfh/1%20CUGH%202020%20eBook_Abstracts_Global%20Health%20Education.pdf?dl=0).11th Annual Consortium of Universities for Global Health Conference.18–20(Arpil).

6. Kimani Peter, **Andrew Koech**, Nyambura Sarah. 2018.[Oral]*Spatial Analysis of Child Mortality in Kenya*.13th JKUAT Scientific, Technological, and Industrialization Conference.15–16 (November) 2018.


# **WORKSHOPS**

**Survival Analysis of Cancer Epidemiology Workshop.** \hfill Nairobi, Kenya

  *University of Nairobi* \hfill 21 – 22 Oct. 2019

**Advanced Biostatistical Methods: Multivariate models and Cluster Randomized Trials Workshop.** \hfill Eldoret, Kenya

  *Moi University* \hfill 15 – 18 Jul. 2019

**Bayesian Biostatistics Data Analysis: Theory and Practice Workshop.** \hfill Nairobi, Kenya

  *Jomo Kenyatta University of Agriculture and Technology* \hfill 19 – 23 Nov. 2018
  


# **TECHNICAL SKILLS**

  _**R for Everything**_
  
  + Data prepreparation (cleaning and wrangling) and statistical analysis/exploratory visualization
with R Markdown (advanced dplyr and ggplot2 package applications)
  + Reproducible and replicable presentation and paper generation with R Markdown
  + Version control using Git and Github with Rstudio
 
  _**Other (non-R) Technical Skills**_
  
  + MySQL
  + Stata
  + Linux
  + Windows
  
  _**Certifications**_
  
  + SAS Certified Specialist: Base Programming Using SAS 9.4

# **NON-TECHNICAL SKILLS**

  _**Spoken Languages**_
  
  + English (native)
  + Deutsche (A2)
  + Swahili (native)
