---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
    keep_tex: TRUE
geometry: margin=1in

title: "CV"
author: Koech Andrew 

jobtitle: "Masters Student, University of Bremen"
address: "Spittaler Strasse 1A-3.02 · 28359 · Bremen, Germany"
fontawesome: yes
linkedin: andrewkoech
email: koech@uni-bremen.de
github: koechandy
phone: "+49 1 777 892 226"
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 13pt
linkcolor: blue
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# **RESEARCH INTERESTS**

  + _Machine Learning, Bayesian statistics, Design and analysis of dose-response experiments, Statistical methods for clinical trials_

# **EDUCATION**

*University of Bremen* \hfill _Bremen, Germany_

  + **M.Sc** in Medical Biometry/Biostatistics \hfill Oct. 2022 - Mar. 2025
      
      + Available for an internship between September 2024 and March 2025.
      
      + “A spatial analysis of local and temporal associations between area-level socio-economic factors and antibiotic prescription rates in Germany” \hfill Ongoing
  
*Jomo Kenyatta University of Agriculture and Technology* \hfill _Nairobi, Kenya_

  + **B.Sc** in Biostatistics \hfill Sept. 2014 - Aug. 2018
  
      + “Spatial Analysis of Child Mortality in Kenya”
  
# **EMPLOYMENT**

<!-- *DKFZ German Cancer Research Center* \hfill _Heidelberg, Deutschland_ -->

<!--   **Intern** \hfill Apr. 2024 - Jul. 2024 -->

<!--   + Coding of Bayesian Highest Posterior Density Intervals. -->

*International Cancer Institute (ICI)* \hfill _Eldoret, Kenya_

  **Biostatistician** \hfill Aug. 2019 - Nov. 2020
  
  + Designed surveys to assess health issues in non-communicable diseases.
  + Wrote statistical analysis plans for surveys to assess health issues in NCDs.
  + Prepared five articles for publication and presentation at local and international scientific conferences.
  + Wrote three research proposals and grant applications for submission to Pfizer and Novartis.
  + Worked with investigators to formalize analysis plans and reporting specifications.
  + Developed statistical analysis plans and wrote program code to analyze data using Stata and R.
  + Collated and submitted clinical trial documents for review of two Norvatis clinical trials.

*AMPATH Oncology Institute* \hfill _Eldoret, Kenya_

  **Research Assistant** \hfill Sept. 2018 - Jul. 2019
  
  + Oversaw registration of patients for cervical and breast cancer screening.
  + Conducted random checks for data completeness and accuracy.
  + Coded data as necessary prior to data entry using master coding lists.
  + Identified appropriate statistical tests for analyzing and modeling oncology data.
  + Compiled reports, charts and graphs that describe and interpret findings of analyses

# **CONFERENCE PRESENTATIONS**

1. **Koech, Andrew**, Emma Achieng, Edwin Odoyo, Dennis Munene, and Fredrick Chite Asirwa.
2020.[Virtual Poster](https://doi.org/10.1158/1538-7755.DISP20-PO-249) “Abstract PO-249: Implementing Community Cervical Mass Screenings in Low-Middle-Income Countries: A Project Implemented by the Blueprint for Success Program, International Cancer Institute in Kenya.” Cancer Epidemiology, Biomarkers & Prevention 29 (December): PO–249. 

2. Kitur, Gloria, Emmah Achieng, Fredrick Chite Asirwa, Edwin Odoyo, and **Andrew Koech**. 2020.[Virtual Poster](https://doi.org/10.1158/1538-7755.DISP20-PO-028)
“Abstract PO-028: Role of Community Outreach Activities in Cancer Prevention in Kenya.”
Cancer Epidemiology, Biomarkers & Prevention 29 (December): PO–028. 

3. Muchiri, Anthony, Gloria Kitur, Hussein Elias, **Andrew Koech**, and Chite Asirwa. 2020.[Virtual Poster](https://doi.org/10.1158/1538-7755.DISP20-PO-047) “Abstract
PO-047: The Role of Virtual Tumor Boards in Improving Patient Outcomes in Rural Settings
of Sub-Saharan Africa.” Cancer Epidemiology, Biomarkers & Prevention 29 (December): PO–047.

4. Sigu, Lamech, Fredrick Chite, Emma Achieng, and **Andrew Koech**. 2020.[Virtual Poster](https://doi.org/10.1200/GO.20.54000) “Setting up
Telemedicine: Internet of Things to Support Rural Oncology Clinics in a Low- and Middle-
Income Country—a Pilot Project in Kenya.” 6 (July):58–58.

5. **Andrew Koech**, Rose Njogu, Emma Achieng, Gloria Kitur, Chizi Kiti, Chite Asirwa.“Abstract : Setting Up Tools for Collecting Quality Data at The International Cancer Institute, Kenya - Learning from other Cancer Institutes, Registries and Cancer Clinics.”2020.[Conference canceled](https://www.dropbox.com/s/lq0owvwya6dcjfh/1%20CUGH%202020%20eBook_Abstracts_Global%20Health%20Education.pdf?dl=0).11th Annual Consortium of Universities for Global Health Conference.18–20(April).

6. Kimani Peter, **Andrew Koech**, Nyambura Sarah. 2018.[Oral] *Spatial Analysis of Child Mortality in Kenya*.13th JKUAT Scientific, Technological, and Industrialization Conference.15–16 (November) 2018.


# **WORKSHOPS**

**Survival Analysis of Cancer Epidemiology. ** \hfill Nairobi, Kenya

  *University of Nairobi* (Facilitators: Prof. Bernard Rachet, Dr. Aurelien Belot) \hfill 21 – 22 Oct. 2019

**Advanced Biostatistical Methods: Multivariate models and Cluster Randomized Trials. ** \hfill Eldoret, Kenya

  *Moi University* (Facilitator: Prof. Joseph Hogan) \hfill 15 – 18 Jul. 2019 

**Bayesian Biostatistics Data Analysis: Theory and Practice. ** \hfill Nairobi, Kenya

  *Jomo Kenyatta University of Agriculture and Technology* (Facilitator: Prof. Emmanuel Lesaffre) \hfill 19 – 23 Nov. 2018 
  


# **TECHNICAL SKILLS**

  _**R for Everything**_
  
  + Data pre-preparation (cleaning and wrangling) and statistical analysis/exploratory visualization
with R Markdown.
  + Reproducible and replicable presentation and paper generation with R Markdown.
  + Version control using Git and Github with Rstudio.
 
  _**Other (non-R) Technical Skills**_
  
  + SAS
  + Linux
  + Windows
  
# **NON-TECHNICAL SKILLS**

  _**Spoken Languages**_
  
  + Deutsche (A2)
  + English (fluent)

  <!-- _**Certifications**_ -->

  <!-- + SAS Certified Specialist: Base Programming Using SAS 9.4 -->
  <!-- + SAS Certified Clinical Trials Programmer Using SAS 9.4 -->
  
# **SERVICE**

  _**Memberships**_
  
<!-- International Biometric Society - Deutsche Region (IBS-DR) \hfill Member -->

PSI - Statisticians in the Pharmaceutical Industry \hfill Member